### ISSUE TITLE
Exception in thread "main" java.lang.IllegalAccessError

### ISSUE THREAD

**Issue by MasterAqu** [Ravaelles/Atlantis#15]
After compile a project - I've recieved a msg of missing path to bwapi.ini. I've finded file path in code and added it. After that this msg pop up aaaand I can't figure out what to do... I've got a knowledge to print "hello world". Can anyone assist? 

Exception in thread "main" java.lang.IllegalAccessError: class bwapi.WrappedBuffer (in unnamed module @0x27c20538) cannot access class sun.nio.ch.DirectBuffer (in module java.base) because module java.base does not export sun.nio.ch to unnamed module @0x27c20538
	at bwapi.WrappedBuffer.<init>(WrappedBuffer.java:20)
	at bwapi.ClientData.<init>(ClientData.java:6)
	at bwapi.Client.connect(Client.java:203)
	at bwapi.Client.reconnect(Client.java:90)
	at bwapi.BWClient.startGame(BWClient.java:45)
	at bwapi.BWClient.startGame(BWClient.java:35)
	at atlantis.Atlantis.run(Atlantis.java:435)
	at main.Main.main(Main.java:48)

**Comment by MasterAqu** [comment]
Find a pass over this problem on stackoverflow: open 'edit run/debug configurations' dialog  -> Modify options -> Add VM options -> copy this into VM Options dialog: --add-opens=java.base/sun.nio.ch=ALL-UNNAMED. 
Chaoslauncher won't start with main run.
