### ISSUE TITLE
Exception on running of Main

### ISSUE THREAD

**Issue by desiguel** [Ravaelles/Atlantis#2]
Ever get this error when running Main?

Native code library failed to load.java.lang.UnsatisfiedLinkError: C:\Users\me\github\Atlantis\client-bridge-x86.dll: Can't find dependent libraries

 I've had the really basic SSCAIT bot running before so I'm pretty sure I have everything installed ok.

**Comment by Ravaelles** [comment]
Make sure that you use Java x86 (ensure in the project properties), that's almost certainly the issue here.

**Comment by saityoukou** [comment]
the same problem.
and i set below not work
            System.setProperty("java.library.path", ".");
            java.lang.reflect.Field fieldSysPath = ClassLoader.class.getDeclaredField("sys_paths");
            fieldSysPath.setAccessible(true);
            fieldSysPath.set(null, null);

Exception in thread "main" java.lang.UnsatisfiedLinkError: E:\eclipse-workspace\Atlantis\client-bridge-x86.dll: Can't find dependent libraries
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1880)
    at java.lang.Runtime.loadLibrary0(Runtime.java:849)
    at java.lang.System.loadLibrary(System.java:1088)
    at jnibwapi.JNIBWAPI.<clinit>(JNIBWAPI.java:85)
    at atlantis.Atlantis.<init>(Atlantis.java:87)
    at main.Main.main(Main.java:24)

**Comment by Ravaelles** [comment]
Please let me know if using:
- 32-bit Windows
- 32-bit Java
  Solved this problem as I expect it should have. 

This isn't strictly related to Atlantis (but to JNIBWAPI), however please let me know if it had finally worked for both of you.

**Comment by desiguel** [comment]
Unfortunately I couldn't get this to work for me (64 bit Windows, 32 bit Java), however I am using your your source as the base for another bot ported to BWAPI Mirror. Hope this is ok?

**Comment by Ravaelles** [comment]
Sure it's ok! The idea behind is to help people start with the fundamentals, which can be extremely tedious and frustrating. 
By the way I hope that Atlantis will be ported to BWMirror soon, so this problem should be... well, irrelevant as BWMirror works a bit differently.
